# Generated by Django 2.2.24 on 2021-07-15 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_app_plan_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='subscription',
        ),
        migrations.AddField(
            model_name='app',
            name='subscription',
            field=models.ManyToManyField(blank=True, related_name='app_subscription', to='home.Subscription'),
        ),
        migrations.RemoveField(
            model_name='app',
            name='user',
        ),
        migrations.AddField(
            model_name='app',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='app_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
