# Generated by Django 2.2.24 on 2021-07-15 19:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_auto_20210715_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='app',
        ),
        migrations.AddField(
            model_name='subscription',
            name='app',
            field=models.ManyToManyField(blank=True, related_name='subscription_app', to='home.App'),
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ManyToManyField(blank=True, related_name='subscription_plan', to='home.Plan'),
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='subscription_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
