# Generated by Django 2.2.24 on 2021-07-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210715_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='subscription',
        ),
        migrations.AddField(
            model_name='app',
            name='subscription',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
