# Generated by Django 2.2.24 on 2021-07-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210723_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='screenshot',
            field=models.URLField(blank=True, editable=False, null=True),
        ),
    ]
