# Generated by Django 2.2.24 on 2021-07-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210723_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
