# Generated by Django 2.2.24 on 2021-07-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210723_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='app',
            field=models.IntegerField(),
        ),
    ]
